### ISSUE TITLE
[Question] Can you use an IRC message text as a variable?

### ISSUE THREAD

**Issue by ndemon** [alejandro5042/Run-IrcBot#11]
EX: 

```
param ($Message, $Bot)

switch -regex ($Message.Text)
{
    "This is a variable"   { storeasvariable }
    "Say Variable" {$Variable}**
}
```

**Comment by alejandro5042** [comment]
Yes you can! See: https://github.com/alejandro5042/Run-IrcBot#stateful-bots

**Comment by ndemon** [comment]
@alejandro5042 I'm confused, it seems that the section that you pointed me to says how to use and preserve variables but not how to store messages as variables.

Thank You.

**Comment by alejandro5042** [comment]
Can't you simply store `$Message.Text` in a `$Bot.State.PreviousMessageText` variable?

Do you want to capture a variable and output it later? This should work: (disclaimer: didn't test)

```ps
'This is a variable: (?<value>.*)' { $Bot.State.Variable = $Matches.value }
'print var' { $Bot.State.Variable }
```

**Comment by ndemon** [comment]
@alejandro5042 Thanks!
